service: p-payment

provider:
  name: azure
  location: North Europe
  environment:
    s-salesforceURL: https://s-salesforce.azurewebsites.net/api/client/
    s-paypalURL: https://s-paypal.azurewebsites.net/api/payment/paypal
plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  processPayment:
    handler: processPayment.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          methods:
            - post
          route: payments
      - http: true
        x-azure-settings:
          direction: out
          name: res