service: x-ecommerce

provider:
  name: azure
  location: North Europe
  environment:
    p-paymentURL: https://p-payment.azurewebsites.net/api/payments

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  payment:
    handler: payment.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          methods:
            - post
          route: payment
      - http: true
        x-azure-settings:
          direction: out
          name: res