service: s-paypal

provider:
  name: azure
  location: North Europe

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  payment:
    handler: payment.handler
    package:
      artifact: .serverless/payment.zip
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          methods:
            - post
          route: payment/paypal
      - http: true
        x-azure-settings:
          direction: out
          name: res